# route:
#     receiver: 'slack'

# receivers:
#     - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             text: "{{ .CommonAnnotations.description }}"
#             username: 'prometheus'
#             channel: '#awsdeploy'
#             api_url: 'https://hooks.slack.com/services/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'